/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.18
 * Generated at: 2026-03-31 11:36:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import java.time.format.DateTimeFormatter;
import org.example.domain.entity.Post;
import org.example.domain.entity.Comment;

public final class comment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("org.example.domain.entity.Post");
    _jspx_imports_classes.add("java.time.format.DateTimeFormatter");
    _jspx_imports_classes.add("org.example.domain.entity.Comment");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    Post post = (Post) request.getAttribute("post");
    List<Comment> comments = (List<Comment>) request.getAttribute("comments");
    DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"fr\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Détail du Post</title>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./style/comment.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <h1>Détail du Post</h1>\r\n");
      out.write("\r\n");
 if (post != null) { 
      out.write("\r\n");
      out.write("    <!-- Affichage du détail du post -->\r\n");
      out.write("    <div id=\"post-detail\">\r\n");
      out.write("        <h2>");
      out.print( post.getContent() );
      out.write("</h2>\r\n");
      out.write("        <p><em>Posté par ");
      out.print( post.getAuthorName() );
      out.write(" le ");
      out.print( post.getCreatedAt() );
      out.write("</em></p>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"back-nav\">\r\n");
      out.write("        <h2><a href=\"");
      out.print( request.getContextPath() );
      out.write("/feed\" class=\"back-link\"> Retour au fil d'actualité</a></h2>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Affichage des commentaires -->\r\n");
      out.write("    <div id=\"comments\">\r\n");
      out.write("        <h3>Commentaires</h3>\r\n");
      out.write("    ");
 if (comments != null && !comments.isEmpty()) { 
            for (Comment comment : comments) { 
      out.write("\r\n");
      out.write("                <div class=\"comment\">\r\n");
      out.write("                    <strong>");
      out.print( comment.getAuthorName() );
      out.write("</strong> ");
      out.print( comment.getContent() );
      out.write("<br>\r\n");
      out.write("                    <span><em>");
      out.print( comment.getCreatedAt() != null ? comment.getCreatedAt().format(dateFormatter) : "Date indisponible" );
      out.write("</em></span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <hr>\r\n");
      out.write("    ");
      }
       } else { 
      out.write("\r\n");
      out.write("        <p>Aucun commentaire pour le moment.</p>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Formulaire pour créer un nouveau commentaire -->\r\n");
      out.write("    <div id=\"new-comment\">\r\n");
      out.write("        <h3>Ajouter un commentaire</h3>\r\n");
      out.write("        <form action=\"");
      out.print( request.getContextPath() );
      out.write("/comments\" method=\"post\">\r\n");
      out.write("            <input type=\"hidden\" name=\"postId\" value=\"");
      out.print( post.getId() );
      out.write("\">\r\n");
      out.write("            <label for=\"content\">Commentaire :</label>\r\n");
      out.write("            <textarea id=\"content\" name=\"content\" rows=\"4\" cols=\"50\" required></textarea><br>\r\n");
      out.write("            <button type=\"submit\">Envoyer</button>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
 } else { 
      out.write("\r\n");
      out.write("    <p>Post introuvable.</p>\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
